app1/urls.py
# from django.urls import path
# from . import views

# app_name = 'app1'

# urlpatterns = [
#     path("app1/demo/", views.translate, name="demo"),
# ]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("english.urls")),
    path("", include("jojo.urls")),
    # path("", include("app1.urls")),
    path("accounts/", include("allauth.urls")),
]

english/urls.py
from django.urls import path

from . import views

app_name = "english"

urlpatterns = [
    # path('',views.IndexView.as_view(),name='index'),
    path(
        "playlist/create/", views.PlaylistCreateView.as_view(), name="playlist_create"
    ),
    path("", views.PlaylistListView.as_view(), name="playlist_list"),
    path("card/create/", views.CardCreateView.as_view(), name="card_create"),
    path("card/list/<int:pk>/", views.card_list, name="card_list"),
    path(
        "playlist/delete/<int:pk>",
        views.PlaylistDeleteView.as_view(),
        name="playlist_delete",
    ),
    path("card/like/", views.likeview, name="like"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("detail/<str:isbn>", views.DetailView.as_view(), name="detail"),
    path("deepl/", views.DeeplView.as_view(), name="deepl"),
]

english/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.


class Playlist(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("created_at",)


class Card(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    word = models.CharField(max_length=30)
    ja_word = models.CharField(max_length=100)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    memo = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.word

    @classmethod
    def get_words(cls,pk,word):
        return Card.objects.filter(word_get=word).exclude(pk=pk)

    class Meta:
        ordering = ("created_at",)


class Like(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)

english/forms.py
from django import forms
from .models import Playlist, Card


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ("title",)


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = (
            "word",
            "ja_word",
            "memo",
            "playlist",
        )

    def clean(self):
        word = self.cleaned_data["word"]
        card = Card.objects.filter(word=word).exists()
        if card:
            raise forms.ValidationError("すでに入力されています")

        return self.cleaned_data


class SearchForm(forms.Form):
    title = forms.CharField(label="書籍名", max_length=200, required=True)


class DeeplForm(forms.Form):
    text = forms.CharField(
        label="word",
        max_length=200,
        required=True,
        widget=forms.Textarea(attrs={"cols": "80", "rows": "10"}),
    )

english/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.urls import reverse_lazy
from django.http import QueryDict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic import View
from django.db.models import Q
from django.views.generic import CreateView, DetailView, DeleteView, ListView
from .models import Playlist, Card, Like
from accounts.models import CustomUser
from .forms import PlaylistForm, CardForm, SearchForm, DeeplForm
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
import json
import requests
import deepl





def get_api_data(params):
    api = requests.get(SEARCH_URL, params=params).text
    result = json.loads(api)
    items = result["Items"]
    return items


def deepl_data(keyword):
    result = translator.translate_text(keyword, target_lang="JA")
    return result


class PlaylistCreateView(LoginRequiredMixin, CreateView):
    model = Playlist
    template_name = "english/playlist/create.html"
    form_class = PlaylistForm
    success_url = reverse_lazy("english:playlist_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PlaylistListView(LoginRequiredMixin, ListView):
    model = Playlist
    template_name = "english/playlist/list.html"


class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    template_name = "english/card/create.html"
    form_class = CardForm

    def get_success_url(self):
        return reverse_lazy("english:card_list", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PlaylistDeleteView(LoginRequiredMixin, DeleteView):
    model = Playlist
    template_name = "english/playlist/delete.html"

    success_url = reverse_lazy("english:playlist_list")


@login_required
def card_list(request, pk):
    card_lis = Card.objects.filter(user=request.user)
    eng = request.GET.get("eng")

    if eng:
        card_lis = card_lis.filter(Q(word__icontains=eng))

    liked_list = []
    for card in card_lis:
        liked = card.like_set.filter(user=request.user)
        if liked.exists():
            liked_list.append(card.id)

    params = {
        "card_lis": card_lis,
        "liked_list": liked_list,
    }

    return render(request, "english/card/list.html", params)


@login_required
def likeview(request):
    if request.method == "POST":
        card = get_object_or_404(Card, pk=request.POST.get("card_id"))
        user = request.user
        liked = False
        like = Like.objects.filter(card=card, user=user)
        if like.exists():
            like.delete()
        else:
            like.create(card=card, user=user)
            liked = True

        params = {
            "card_id": card.id,
            "liked": liked,
            "count": card.like_set.count(),
        }
    if request.is_ajax():
        return JsonResponse(params)


class IndexView(View):
    def get(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        return render(request, "english/index.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data["title"]
            params = {
                "title": keyword,
                "hits": 30,
            }
            items = get_api_data(params)
            book_data = []
            for i in items:
                item = i["Item"]
                title = item["title"]
                image = item["largeImageUrl"]
                isbn = item["isbn"]
                query = {
                    "title": title,
                    "image": image,
                    "isbn": isbn,
                }
                book_data.append(query)

            return render(
                request,
                "english/search.html",
                {
                    "book_data": book_data,
                    "keyword": keyword,
                },
            )
        return render(request, "english/playlist/list.html", {"form": form})


class DetailView(View):
    def get(self, request, *args, **kwargs):
        isbn = self.kwargs["isbn"]
        params = {"isbn": isbn}

        items = get_api_data(params)
        items = items[0]
        item = items["Item"]
        title = item["title"]
        image = item["largeImageUrl"]
        itemPrice = item["itemPrice"]
        salesDate = item["salesDate"]
        publisherName = item["publisherName"]
        isbn = item["isbn"]
        itemUrl = item["itemUrl"]
        itemCaption = item["itemCaption"]

        book_data = {
            "title": title,
            "image": image,
            "itemPrice": itemPrice,
            "salesDate": salesDate,
            "publisherName": publisherName,
            "isbn": isbn,
            "itemUrl": itemUrl,
            "itemCaption": itemCaption,
        }

        return render(request, "english/detail.html", {"book_data": book_data})


class DeeplView(View):
    def get(self, request, *args, **kwargs):
        form = DeeplForm(request.POST or None)

        return render(request, "english/deepl.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = DeeplForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data["text"]
            items = deepl_data(keyword)
            word_data = items.text

            return render(
                request,
                "english/result.html",
                {
                    "word_data": word_data,
                    "keyword": keyword,
                },
            )
        return render(request, "english/playlist/list.html", {"form": form})

english/templates/english/card/create.html
{%extends 'english/base.html'%}

{%block title%}Create card{%endblock%}

{%block content%}
  <h1>Create Card</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
{%endblock%}

english/templates/english/card/like.html
<form action="{% url 'english:like' %}" method="POST">
    {% csrf_token %}
    {% if card.id in liked_list %}
        <button type="submit" id="like" name="{{card.id}}"><i class="fas fa-lg fa-heart like-red"></i></button>
    {% else %}
        <button type="submit" id="like" name="{{card.id}}"><i class="fas fa-lg fa-heart"></i></button>      
    {% endif %}
</form>
<p name="{{card.id}}-count" class="count"> {{ card.like_set.count }} </p>

english/templates/english/card/list.html
{%extends 'english/base.html'%}

{%block title%}card list{%endblock%}

{%block content%}
  <h1>単語一覧</h1>
  <br>
  <form method="GET" action=" ">
    単語検索：
    <input type="text" name="eng">
    <button class="btn btn-success" type="submit">検索</button>
  </form>
  <a class="btn btn-primary my-3" href="{% url 'english:card_create' %}" role="button">作成</a>
  <div class="card-columns">
    {% for card in card_lis %}
    <a href="#" class="card"></a>
    <div class="card-body">
        <h3 class="card-title text-center">{{ card.word }}</h3>
        <h3 class="card-text text-center">{{card.ja_word}}</h3>
        <p class="card-title text-center text-black-50">{{card.memo}}</p>
        <div class="text-center" id="like">
          {% include 'english/card/like.html' %}
        </div> 
    </div>
    {% endfor %}
  </div>

  <script type="text/javascript">
    $(document).ready(function(event){
      $(document).on('click', '#like', function(event){
          event.preventDefault();
          $.ajax({
              type: 'POST',
              url: "{% url 'english:like' %}",
              data: {
                  'card_id': $(this).attr('name'),
                  'csrfmiddlewaretoken': '{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  selector = document.getElementsByName(response.card_id);
                  if(response.liked){
                      $(selector).html("<i class='fas fa-lg fa-heart like-red'></i>");
                  }
                  else {
                      $(selector).html("<i class='far fa-lg fa-heart'></i>");
                  }
                  selector2 = document.getElementsByName(response.card_id + "-count");
                  $(selector2).text(response.count);
              }
          });
      });
  });
  </script>
{%endblock%}