app1/urls.py
# from django.urls import path
# from . import views

# app_name = 'app1'

# urlpatterns = [
#     path("app1/demo/", views.translate, name="demo"),
# ]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("english.urls")),
    path("", include("jojo.urls")),
    # path("", include("app1.urls")),
    path("accounts/", include("allauth.urls")),
]

english/urls.py
from django.urls import path

from . import views

app_name = "english"

urlpatterns = [
    # path('',views.IndexView.as_view(),name='index'),
    path(
        "playlist/create/", views.PlaylistCreateView.as_view(), name="playlist_create"
    ),
    path("", views.PlaylistListView.as_view(), name="playlist_list"),
    path("card/create/", views.CardCreateView.as_view(), name="card_create"),
    path("card/list/<int:pk>/", views.card_list, name="card_list"),
    path(
        "playlist/delete/<int:pk>",
        views.PlaylistDeleteView.as_view(),
        name="playlist_delete",
    ),
    path("card/like/", views.likeview, name="like"),
    path("index/", views.IndexView.as_view(), name="index"),
    path("detail/<str:isbn>", views.DetailView.as_view(), name="detail"),
    path("deepl/", views.DeeplView.as_view(), name="deepl"),
]

jojo/urls.py
from django.urls import path

from . import views

app_name = "jojo"

urlpatterns = [path("jojo/list/", views.jojo_change, name="jojo_list")]

english/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.


class Playlist(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("created_at",)


class Card(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    word = models.CharField(max_length=30)
    ja_word = models.CharField(max_length=100)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    memo = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.word

    @classmethod
    def get_words(cls,pk,word):
        return Card.objects.filter(word_get=word).exclude(pk=pk)

    class Meta:
        ordering = ("created_at",)


class Like(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)

english/forms.py
from django import forms
from .models import Playlist, Card


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ("title",)


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = (
            "word",
            "ja_word",
            "memo",
            "playlist",
        )

    def clean(self):
        word = self.cleaned_data["word"]
        card = Card.objects.filter(word=word).exists()
        if card:
            raise forms.ValidationError("すでに入力されています")

        return self.cleaned_data


class SearchForm(forms.Form):
    title = forms.CharField(label="書籍名", max_length=200, required=True)


class DeeplForm(forms.Form):
    text = forms.CharField(
        label="word",
        max_length=200,
        required=True,
        widget=forms.Textarea(attrs={"cols": "80", "rows": "10"}),
    )

english/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.urls import reverse_lazy
from django.http import QueryDict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic import View
from django.db.models import Q
from django.views.generic import CreateView, DetailView, DeleteView, ListView
from .models import Playlist, Card, Like
from accounts.models import CustomUser
from .forms import PlaylistForm, CardForm, SearchForm, DeeplForm
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
import json
import requests
import deepl





def get_api_data(params):
    api = requests.get(SEARCH_URL, params=params).text
    result = json.loads(api)
    items = result["Items"]
    return items


def deepl_data(keyword):
    result = translator.translate_text(keyword, target_lang="JA")
    return result


class PlaylistCreateView(LoginRequiredMixin, CreateView):
    model = Playlist
    template_name = "english/playlist/create.html"
    form_class = PlaylistForm
    success_url = reverse_lazy("english:playlist_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PlaylistListView(LoginRequiredMixin, ListView):
    model = Playlist
    template_name = "english/playlist/list.html"


class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    template_name = "english/card/create.html"
    form_class = CardForm

    def get_success_url(self):
        return reverse_lazy("english:card_list", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PlaylistDeleteView(LoginRequiredMixin, DeleteView):
    model = Playlist
    template_name = "english/playlist/delete.html"

    success_url = reverse_lazy("english:playlist_list")


@login_required
def card_list(request, pk):
    card_lis = Card.objects.filter(user=request.user)
    eng = request.GET.get("eng")

    if eng:
        card_lis = card_lis.filter(Q(word__icontains=eng))

    liked_list = []
    for card in card_lis:
        liked = card.like_set.filter(user=request.user)
        if liked.exists():
            liked_list.append(card.id)

    params = {
        "card_lis": card_lis,
        "liked_list": liked_list,
    }

    return render(request, "english/card/list.html", params)


@login_required
def likeview(request):
    if request.method == "POST":
        card = get_object_or_404(Card, pk=request.POST.get("card_id"))
        user = request.user
        liked = False
        like = Like.objects.filter(card=card, user=user)
        if like.exists():
            like.delete()
        else:
            like.create(card=card, user=user)
            liked = True

        params = {
            "card_id": card.id,
            "liked": liked,
            "count": card.like_set.count(),
        }
    if request.is_ajax():
        return JsonResponse(params)


class IndexView(View):
    def get(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        return render(request, "english/index.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data["title"]
            params = {
                "title": keyword,
                "hits": 30,
            }
            items = get_api_data(params)
            book_data = []
            for i in items:
                item = i["Item"]
                title = item["title"]
                image = item["largeImageUrl"]
                isbn = item["isbn"]
                query = {
                    "title": title,
                    "image": image,
                    "isbn": isbn,
                }
                book_data.append(query)

            return render(
                request,
                "english/search.html",
                {
                    "book_data": book_data,
                    "keyword": keyword,
                },
            )
        return render(request, "english/playlist/list.html", {"form": form})


class DetailView(View):
    def get(self, request, *args, **kwargs):
        isbn = self.kwargs["isbn"]
        params = {"isbn": isbn}

        items = get_api_data(params)
        items = items[0]
        item = items["Item"]
        title = item["title"]
        image = item["largeImageUrl"]
        itemPrice = item["itemPrice"]
        salesDate = item["salesDate"]
        publisherName = item["publisherName"]
        isbn = item["isbn"]
        itemUrl = item["itemUrl"]
        itemCaption = item["itemCaption"]

        book_data = {
            "title": title,
            "image": image,
            "itemPrice": itemPrice,
            "salesDate": salesDate,
            "publisherName": publisherName,
            "isbn": isbn,
            "itemUrl": itemUrl,
            "itemCaption": itemCaption,
        }

        return render(request, "english/detail.html", {"book_data": book_data})


class DeeplView(View):
    def get(self, request, *args, **kwargs):
        form = DeeplForm(request.POST or None)

        return render(request, "english/deepl.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = DeeplForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data["text"]
            items = deepl_data(keyword)
            word_data = items.text

            return render(
                request,
                "english/result.html",
                {
                    "word_data": word_data,
                    "keyword": keyword,
                },
            )
        return render(request, "english/playlist/list.html", {"form": form})

english/templates/english/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>English Word</title>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
        <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{%url 'english:playlist_list'%}">Home</a>
                <a class="navbar-brand" href="{%url 'english:index'%}">書籍検索</a>
                <a class="navbar-brand" href="{%url 'english:deepl'%}">翻訳</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {%if user.is_authenticated%}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'account_logout'%}">Log Out</a></li>
                        <form method="GET" action='{%url "jojo:jojo_list" %}'>
                            <input type="text" name="keyword">
                            <button class="btn btn-primary" type="submit">検索</button>
                        </form>
                        {%else%}
                        <li class="nav-item{%block active_signup%}{%endblock%}"><a class="nav-link" href="{%url 'account_signup'%}">Sign Up</a></li>
                        <li class="nav-item{%block active_login%}{%endblock%}"><a class="nav-link" href="{%url 'account_login'%}">Log In</a></li>
                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
            <div class="text-center my-5">
                <h1 class="text-white fs-3 fw-bolder">Your English</h1>
                <p class="text-white-50 mb-0">あなただけの単語帳</p>
            </div>
        </header>
        <!-- Content section-->
        <section class="py-5">
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        {%block content%}
                        {%endblock%}
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

english/templates/english/deepl.html
{%extends 'english/base.html'%}

{%block title%}index{%endblock%}

{%block content%}

<form method="post">
    {%csrf_token%}
    英語入力：
    <input type="text" name='text' placeholder="word">
    <button class="btn btn-success" type="submit">検索</button>
</form>

{%endblock%}

english/templates/english/detail.html
{%extends 'english/base.html'%}

{%block title%}search{%endblock%}

{%block content%}

<div class="my-5">
    <div class="row">
        <div class="col-md-6 text-center">
            <img src="{{book_data.image}}" alt="" class="img-fluid">
        </div>

        <div class="col-md-6 text-center">
            <div class="card">
                <div class="card-body px-2 py-1">
                    <div class="p-4">
                        <h3>{{book_data.title}}</h3>
                        <p class="mb-3">{{book_data.author}}</p>
                        <p class="mt-3">価格: <span class="texx-danger font-weight-bold h3">{{book_data.itemPrice}}</span></p>
                        <a href="{{book_data.itemUrl}}" class="btn btn-primary"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%if book_data.itemCaption%}
    <h5>商品説明</h5>
    <hr>
    <p>{{book_data.itemCaption}}</p>
    <p>ISBN: {{book_data.isbn}}</p>
    {%endif%}
</div>

{%endblock%}

english/templates/english/index.html
{%extends 'english/base.html'%}

{%block title%}index{%endblock%}

{%block content%}

<form method="post">
    {%csrf_token%}
    単語検索：
    <input type="text" name='title' placeholder="書籍名">
    <button class="btn btn-success" type="submit">検索</button>
</form>

{%endblock%}

english/templates/english/result.html
{%extends 'english/base.html'%}

{%block title%}search{%endblock%}

{%block content%}

<div class="text-center my-5">
    <div class="mb-5">
        <h3>翻訳結果</h3>
    </div>
    <div class="text-center">
        <h3>{{keyword}}：{{word_data}}</h3>
    </div>
</div>

{%endblock%}

english/templates/english/search.html
{%extends 'english/base.html'%}

{%block title%}search{%endblock%}

{%block content%}

<div class="text-center my-5">
    <div class="mb-5">
        <h3>{{keyword}}の検索結果</h3>
    </div>
    <div class="row">
        {%for book in book_data %}
        <div class="col-3 mb-3">
            <div class="card img-thumbnail booklist h-100">
                <img src="{{book.image}}" alt="" class="card-image-top card-thum">
                <div class="card-body text-center px-2 py-3">
                    <h5 class="font-weigh-bold">{{book.title}}</h5>
                    <h5>{{book.isbn}}</h5>
                </div>
                <a href="{% url 'english:detail' book.isbn %}" class="stretched-link"></a>
            </div>
        </div>
        {%empty%}
        <p>当てはまるものはありませんでした</p>
        {%endfor%}
    </div>
</div>

{%endblock%}